django_transmission/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^torrents/', include('torrents.urls', namespace='torrents')),
    url(r'^shows/', include('shows.urls', namespace='shows')),
]

shows/urls.py
from django.conf.urls import url

from shows import views

urlpatterns = [
    url(r'^add-series/', views.add_series, name='add_series'),
    url(
        r'^respond-to-selected-series/',
        views.respond_to_selected_series,
        name='respond_to_selected_series',
    )
]

torrents/urls.py
from django.conf.urls import url

from torrents import views

urlpatterns = [
    url(r'^active/', views.active, name='active'),
]

shows/models.py
import datetime

from django.db import models


class Series(models.Model):
    name = models.CharField(max_length=255, unique=True)
    download_after = models.DateField(default=datetime.date.today)
    imdb_id = models.CharField(max_length=255, unique=True)
    tvdb_id = models.CharField(
        max_length=255,
        unique=True,
        null=True,
        blank=True,
    )
    eztv_id = models.PositiveIntegerField(
        unique=True,
        null=True,
        blank=True,
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'series'

    def save(self, *args, **kwargs):
        self.tvdb_id = self.tvdb_id or None
        self.eztv_id = self.eztv_id or None
        super(Series, self).save(*args, **kwargs)


class Episode(models.Model):
    series = models.ForeignKey(Series, on_delete=models.CASCADE)
    season = models.PositiveIntegerField()
    episode = models.PositiveIntegerField()
    air_date = models.DateField()

    def __str__(self):
        return '{series} S{season:02d}E{episode:02d}'.format(
            series=self.series.name,
            season=self.season,
            episode=self.episode,
        )

    class Meta:
        unique_together = 'series', 'season', 'episode'
        get_latest_by = 'air_date'

torrents/models.py
from django.db import models

from shows.models import Episode


class Status(models.Model):
    name = models.CharField(max_length=255, unique=True)
    label = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'statuses'


class Torrent(models.Model):
    episode = models.OneToOneField(Episode, on_delete=models.CASCADE)
    status = models.ForeignKey(Status, on_delete=models.CASCADE)
    torrent_hash = models.CharField(
        max_length=255, unique=True, null=True, blank=True,
    )
    magnet_link = models.CharField(
        max_length=511, unique=True, null=True, blank=True,
    )

    def __str__(self):
        return 'Torrent of {episode}'.format(episode=self.episode)

    def save(self, *args, **kwargs):
        self.torrent_hash = self.torrent_hash or None
        self.magnet_link = self.magnet_link or None
        super(Torrent, self).save(*args, **kwargs)

shows/forms.py
from django import forms


class AddSeriesForm(forms.Form):
    series_name = forms.CharField(label='Series name', max_length=255)

shows/views.py
from django.shortcuts import render

from shows.logic import *
from shows.forms import AddSeriesForm


def add_series(request):
    if request.method == 'POST':
        form = AddSeriesForm(request.POST)
        if form.is_valid():
            series_name = form.cleaned_data['series_name']
            candidates = find_imdb_candidates(series_name)
            if candidates:
                context = {'candidates': candidates}
                return render(
                    request,
                    'shows/select-series-to-add.html',
                    context,
                )

    context = {'form': AddSeriesForm()}
    return render(request, 'shows/add-series.html', context)


def respond_to_selected_series(request):
    series_info = request.GET['series'].strip().split(',')
    series_name, result = add_selected_series(*series_info)
    context = {'series': series_name, 'result': result}
    return render(request, 'shows/add-series-result.html', context)

torrents/views.py
import json
from django.http import HttpResponse
from django.shortcuts import render

from torrents.logic import active_torrents_info


def active(request):
    if request.is_ajax():
        content = {'torrents': active_torrents_info()}
        return HttpResponse(
            json.dumps(content),
            content_type='application/json',
        )
    return render(request, 'torrents/active.html')

django_transmission/templates/django_transmission/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}dj-trans{% endblock %}</title>
    {% block extra-head %}{% endblock %}
</head>
<body>
{% block body %}{% endblock %}
</body>
</html>

shows/templates/shows/add-series-result.html
{% extends 'shows/base.html' %}

{% block title %}Add a show{% endblock %}

{% block body %}
    {% if result %}
        {{ series }} was added successfully!
        You can <a href="{% url "shows:add_series" %}">add another series</a>.
    {% else %}
        Unfortunately, {{ series }} was not added.
        Go <a href="{% url "shows:add_series" %}">here</a> to retry.
    {% endif %}
{%  endblock %}

shows/templates/shows/add-series.html
{% extends 'shows/base.html' %}

{% block title %}Add a show{% endblock %}

{% block body %}
    <h2 class="page-description">Add a new show.</h2>
    <form action="{% url "shows:add_series" %}" method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Submit"/>
    </form>
{% endblock %}

shows/templates/shows/base.html
{% extends 'django_transmission/base.html' %}
{% load staticfiles %}

{% block extra-head %}
    <link rel="stylesheet" type="text/css" href="{% static "css/shows.css" %}" media="screen" />
{% endblock %}

shows/templates/shows/select-series-to-add.html
{% extends 'shows/base.html' %}

{% block title %}Add a show{% endblock %}

{% block body %}
    <h2 class="page-description">Select a show to add.</h2>
    <form action="{% url "shows:respond_to_selected_series" %}">
        {% for candidate in candidates %}
            <input class="series-radio-item" type="radio" name="series" value="{{ candidate.name }},{{ candidate.imdb_id }},{{ candidate.tvdb_id }}">
                <img class="series-thumbnail" src="{{ candidate.img }}" alt="HTML5 Icon">
                <a href="{{ candidate.link }}">{{ candidate.name }}</a>
                ({{ candidate.year }})
                <br>
        {% endfor %}
    <input class="submit-button" type="submit" value="add">
    </form>

{% endblock %}

torrents/templates/torrents/active.html
{% extends 'torrents/base.html' %}
{% load staticfiles %}

{% block title %}Active Torrents{% endblock %}

{% block extra-head %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static "css/vendor/dataTables.jqueryui.min.css" %}" media="screen" />
    <script type="text/javascript" src="{% static "js/vendor/jquery.min.js" %}"></script>
    <script type="text/javascript" src="{% static "js/vendor/jquery.dataTables.min.js" %}"></script>
    <script type="text/javascript" src="{% static "js/vendor/dataTables.jqueryui.min.js" %}"></script>
    <script type="text/javascript" src="{% static "js/tables.js" %}">
    </script>
{% endblock %}

{% block body %}
    <h2 class="page-description">This is the page of the active torrents.</h2>
    <table class="torrent-table">
        <thead>
            <tr>
                <th>Name</th>
                <th>Ratio</th>
                <th>Progress</th>
            </tr>
        </thead>
        <tbody></tbody>
    </table>
{% endblock %}

torrents/templates/torrents/base.html
{% extends 'django_transmission/base.html' %}
{% load staticfiles %}

{% block extra-head %}
    <link rel="stylesheet" type="text/css" href="{% static "css/torrents.css" %}" media="screen" />
{% endblock %}